openapi: 3.0.3
info:
  title: Sample User API
  description: API for managing users
  version: 1.0.0
paths:
  /person/{personId}:
    get:
      summary: Get user by ID
      description: Retrieve a single user by their ID
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the user to retrieve
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                $ref: 'AccountComponents.yaml#/components/schemas/Account'
        '404':
          description: User not found